[2022-11-29 03:48:05,593] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T03:48:04.504107+00:00 [queued]>
[2022-11-29 03:48:05,600] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T03:48:04.504107+00:00 [queued]>
[2022-11-29 03:48:05,600] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 03:48:05,600] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 03:48:05,600] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 03:48:05,609] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 03:48:04.504107+00:00
[2022-11-29 03:48:05,613] {standard_task_runner.py:52} INFO - Started process 4690 to run task
[2022-11-29 03:48:05,616] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T03:48:04.504107+00:00', '--job-id', '994', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmpjumka6hg', '--error-file', '/tmp/tmpmawqud0d']
[2022-11-29 03:48:05,616] {standard_task_runner.py:77} INFO - Job 994: Subtask getDataToLocal
[2022-11-29 03:48:05,656] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T03:48:04.504107+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 03:48:05,694] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T03:48:04.504107+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T03:48:04.504107+00:00
[2022-11-29 03:48:08,706] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 03:48:08,714] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T034804, start_date=20221129T034805, end_date=20221129T034808
[2022-11-29 03:48:08,761] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 03:48:08,790] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
