[2022-11-29 04:05:52,182] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T04:05:51.584992+00:00 [queued]>
[2022-11-29 04:05:52,190] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T04:05:51.584992+00:00 [queued]>
[2022-11-29 04:05:52,190] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 04:05:52,190] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 04:05:52,190] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 04:05:52,199] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 04:05:51.584992+00:00
[2022-11-29 04:05:52,203] {standard_task_runner.py:52} INFO - Started process 5523 to run task
[2022-11-29 04:05:52,206] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'getDataToLocal', 'manual__2022-11-29T04:05:51.584992+00:00', '--job-id', '1024', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmpfx_h4por', '--error-file', '/tmp/tmp263woxmf']
[2022-11-29 04:05:52,207] {standard_task_runner.py:77} INFO - Job 1024: Subtask getDataToLocal
[2022-11-29 04:05:52,248] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.getDataToLocal manual__2022-11-29T04:05:51.584992+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 04:05:52,289] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T04:05:51.584992+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T04:05:51.584992+00:00
[2022-11-29 04:05:56,554] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 04:05:56,562] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=getDataToLocal, execution_date=20221129T040551, start_date=20221129T040552, end_date=20221129T040556
[2022-11-29 04:05:56,593] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 04:05:56,622] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
