[2022-11-28 19:03:55,339] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: using_pandas_demo.getDataToLocal manual__2022-11-28T19:03:53.888771+00:00 [queued]>
[2022-11-28 19:03:55,349] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: using_pandas_demo.getDataToLocal manual__2022-11-28T19:03:53.888771+00:00 [queued]>
[2022-11-28 19:03:55,349] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-28 19:03:55,349] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-28 19:03:55,349] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-28 19:03:55,362] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-28 19:03:53.888771+00:00
[2022-11-28 19:03:55,366] {standard_task_runner.py:52} INFO - Started process 417 to run task
[2022-11-28 19:03:55,370] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'using_pandas_demo', 'getDataToLocal', 'manual__2022-11-28T19:03:53.888771+00:00', '--job-id', '398', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmp_er70hb0', '--error-file', '/tmp/tmpv471x973']
[2022-11-28 19:03:55,371] {standard_task_runner.py:77} INFO - Job 398: Subtask getDataToLocal
[2022-11-28 19:03:55,427] {logging_mixin.py:109} INFO - Running <TaskInstance: using_pandas_demo.getDataToLocal manual__2022-11-28T19:03:53.888771+00:00 [running]> on host acb48b0a6e0d
[2022-11-28 19:03:55,486] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=using_pandas_demo
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T19:03:53.888771+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-28T19:03:53.888771+00:00
[2022-11-28 19:03:59,014] {python.py:175} INFO - Done. Returned value was: None
[2022-11-28 19:03:59,049] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=using_pandas_demo, task_id=getDataToLocal, execution_date=20221128T190353, start_date=20221128T190355, end_date=20221128T190359
[2022-11-28 19:03:59,120] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-28 19:03:59,240] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
